### PR TITLE
change bounding box values to normalized

### PR DESCRIPTION
**Pull request by BenMacnaughton**
Please ensure you've followed the checklist and provide all the required information *before* requesting a review.

## Required Information

- [x] Reference the issue this is meant to fix or describe it if none exists.
- [x] Full description of changes made.

## Pull Request Checklist

- [x] Coding standards are followed (e.g., [PEP8](https://pep8.org/))
- [x] An entry exists for the container in `docker-compose.yml` or `build.yml`
- [x] The Docker image builds
- [x] The container runs correctly when sent inputs with the changes
- [x] No models or other large files are part of these commits
- [x] A description of the tests already run as part of this PR is present
- [x] CI is set up under `.github/workflows` or is not applicable

### CODE REVIEW

**Comment by BenMacnaughton** [comment]
This has been tested on Unicorn with a number of graphics requests containing text.

**Comment by BenMacnaughton** [comment]
The only change here is to convert the OCR text bounding box to a normalized set of coordinates so that it can be compared against normalized coords from other preprocessors

**Comment by BenMacnaughton** [comment]
Yes this is just to do with the differences between the OCR api and the Read api. (The former returns 2 points always forming a rectangle whereas the latter returns 4 points that can for some arbitrary quadrilateral). Even when we were using the Read api I was not making use of these additional points so I think it's fine

**Review by JRegimbal — APPROVED** [review]

**Comment by JRegimbal** [comment]
@BenMacnaughton the PR to the OCR API is in a ready or near-ready state, right?

**Comment by BenMacnaughton** [comment]
@JRegimbal yes ready as far as I am concerned

**Pull request merged**
