### PR TITLE
Update autour query to include streets and intersections

### PR DESCRIPTION
**Pull request by aidanwilliams09**
Please ensure you've followed the checklist and provide all the required information *before* requesting a review.

## Required Information

- [x] Reference the issue this is meant to fix or describe it if none exists.
- [x] Full description of changes made.

## Pull Request Checklist

- [x] Coding standards are followed (e.g., [PEP8](https://pep8.org/))
- [x] An entry exists for the container in `docker-compose.yml` or `build.yml`
- [x] The Docker image builds
- [x] The container runs correctly when sent inputs with the changes
- [x] No models or other large files are part of these commits
- [x] A description of the tests already run as part of this PR is present

### CODE REVIEW

**Comment by aidanwilliams09** [comment]
Only change made was an update to the Autour query to retrieve information on streets and intersections. The testing conducted was a check on A) whether the query still returned valid results and B) whether the results still satisfied the json schema.

**Comment by jeffbl** [comment]
Did the query return the new content?

**Comment by aidanwilliams09** [comment]
> Did the query return the new content?

Yes, here are a couple of the new results:

{'id': 'AAAM0osQ', 'll': [45.543195, -73.628817], 'cat': 87, 'title': 'Rue Berri & Rue Jarry Est', 'from': 'osmxing', 'rating': 10}
{'id': 'KUonKXye', 'll': [45.54356, -73.627912, 45.543582, -73.627991], 'cat': 89, 'title': 'Rue Lajeunesse', 'from': 'osmsegments'}

**Comment by jeffbl** [comment]
@aidanwilliams09 If you are ready for review, please assign to @jaydeepsingh25

**Comment by BenMacnaughton** [comment]
This has been tested with map requests (both with lat/lon and without) on several locations: preprocessor data returns as expected and all newly added data conforms to Autour schema. End-to-end testing with the browser has not been done but the structure of the request remains the same as for usual maps requests.

**Review by jaydeepsingh25 — APPROVED** [review]

**Pull request merged**
