### PR TITLE
Added schema for action recognition

### PR DESCRIPTION
**Pull request by rohanakut**
Their PR is wrt to #460. The PR tries to create a schema for the action recognition model. The expected output of the schema is as follows

```
{
  "position_action": [
    {
      "ObjectID": 1,
      "possible_action": [
        {
          "action": "feeding",
          "confidence": 0.99
        },
        {
          "action": "mowing the lawn",
          "confidence": 0.59
        }
      ],
      "possible_position": [
        {
          "position": "standing",
          "confidence": 0.99
        }
      ]
    },
    {
      "ObjectID": 2,
      "possible_action": [
        {
          "action": "sleeping",
          "confidence": 0.59
        }
      ],
      "possible_position": [
        {
          "position": "sitting",
          "confidence": 0.99
        }
      ]
    }
  ]
}
```

### CODE REVIEW

**Review by JRegimbal — COMMENTED** [review]
Similar questions as I had with the emotion/age/gender schema. Where is ObjectID coming from and how do you plan to manage disagreements in what other models detect as a person and what this one does? What is the vocabulary defining the actions and positions? Is confidence a meaningful metric here or will we encounter similar problems as we have in the past?

**Comment by rohanakut** [comment]
For the ObjectID, I am planning to use just one single object detector. Whether YOLO would be chosen or Azure is still not decided, but I would only be considering one object detector. This object detector is going to be consistent for all the other preprocessors. 

As for the functionality of this model, this model would be a direct implementation of t[his repository](https://github.com/dronefreak/human-action-classification). As mentioned in the repository, the output of this model would be the position of the person(standing or sitting) , the action performed and the confidence. 

The confidence metric would suffer from the same problem as the previous models as it is the same metric.

**Comment by JRegimbal** [comment]
Alright, still have some concerns here but those are pretty much just repeats of what I said in the other PR.

**Comment by rohanakut** [comment]
closing this PR as it was decided that this schema is not necessary for preprocessor implementation

**Pull request closed without merging**
