### PR TITLE
Include Points of Interest (POIs) to the SVG Layers

### PR DESCRIPTION
**Pull request by samueljohnsegun148**
This PR is to close the issue raised in #607.

Please ensure you've followed the checklist and provide all the required information *before* requesting a review.
If you do not have everything applicable to your PR, it will not be reviewed!
If you don't know what something is or if it applies to you, ask!

Don't delete below this line.

---

## Required Information

- [x] I referenced the issue addressed in this PR.
- [x] I described the changes made and how these address the issue.
- [x] I described how I tested these changes.

## Coding/Commit Requirements

* [x] I followed applicable coding standards (e.g., [PEP8](https://pep8.org/))
* [ ] I have not committed any models or other large files.

## New Component Checklist (**mandatory** for new microservices)

* [ ] I added an entry to `docker-compose.yml` and `build.yml`.
* [ ] I created A CI workflow under `.github/workflows`.

### CODE REVIEW

**Comment by samueljohnsegun148** [comment]
Tested locally and on unicorn with this request:  using ```/var/docker/image/bin/sendimagereq svg-map-request.json http://172.22.0.1:5000/handler'''.

Below is the output. The dots represent the spread of the various points of interest such as intersections, restaurants, etc., along the streets. An additional step may be to include their respective names, but the whole view area may be too congested with text characters.

image

**Comment by JRegimbal** [comment]
PlaceID changes should **not** be part of this PR!

**Comment by JRegimbal** [comment]
Yet again, you are deleting files outside the scope off this PR. Deleting a file does not remove new modifications, it removes the file which is itself a modification. Please [refresh your memory on how to undo modifications](https://git-scm.com/book/en/v2/Git-Basics-Undoing-Things) and do not reassign this until this is a PR that addresses one issue and nothing else.

As an aside, I have no idea why intersections would be classified as points of interest. I'm also not sure if knowing that points of interest exist, but being unable to get any more information on them than that, is remotely useful for debugging.

**Comment by samueljohnsegun148** [comment]
I'm closing this PR in favour of the new one that I have created. https://github.com/Shared-Reality-Lab/IMAGE-server/pull/627/files

**Pull request closed without merging**
