### PR TITLE
Switch Dockerfile to gunicorn for autour and ocr

### PR DESCRIPTION
**Pull request by aidanwilliams09**
Please ensure you've followed the checklist and provide all the required information *before* requesting a review.

## Required Information

- [x] Reference the issue this is meant to fix or describe it if none exists.
- [x] Full description of changes made.

## Pull Request Checklist

- [x] Coding standards are followed (e.g., [PEP8](https://pep8.org/))
- [x] An entry exists for the container in `docker-compose.yml` or `build.yml`
- [x] The Docker image builds
- [x] The container runs correctly when sent inputs with the changes
- [x] No models or other large files are part of these commits
- [x] A description of the tests already run as part of this PR is present
- [x] CI is set up under `.github/workflows` or is not applicable

### CODE REVIEW

**Comment by aidanwilliams09** [comment]
In response to issues #323 #324 
Changed Dockerfiles for autour and ocr to use a gunicorn WSGI server and added gunicorn v20.1.0 to requirements.txt

**Comment by aidanwilliams09** [comment]
Will do, still need to test this on unicorn so I'll add her once that is done.

**Comment by jeffbl** [comment]
Sounds good. Just making sure it isn't being overlooked since there was no assignee on it.

**Comment by aidanwilliams09** [comment]
Rebased with main because of conflicts...should have just resolved the conflicts but this is up to date now anyways.

**Comment by aidanwilliams09** [comment]
Ran the preprocessor on unicorn and still receive valid results so I am under the impression that the switch to gunicorn was successful.

**Comment by aidanwilliams09** [comment]
Because I rebased, just want to draw attention to the files I changed:
The Dockerfile and requirements.txt fiiles in autour and ocr preprocessor

**Comment by jeffbl** [comment]
Checking again if this should go for review now? If so, you need to assign it to the reviewer so that they look at it. I see Jaydeep as a reviewer, but it isn't yet assigned to him, so the assumption is that you're still working on this, and will assign it to him when really ready for the review.

**Comment by aidanwilliams09** [comment]
Didn't realize I needed to assign him the PR and request a review...thanks for catching that

**Comment by jaydeepsingh25** [comment]
@aidanwilliams09 Can you please raise a new PR which includes only your changes. I understand that it is showing too many files because of the rebase, but it also hard to check all the files if change in each of the file is really intentional.
Also, make sure that your PR does not show any changes in schemas submodule, unless it is really intended.

**Pull request closed without merging**
