### PR TITLE
People handler

### LINKED ISSUE #585: people demonstration handler (text only) incorporating emotion, clothing, and celebrity information

### PR DESCRIPTION
**Pull request by rohanakut**
This PR is wrt #469 and will close #585 as well. This handler incorporates all the preprocessors and generates a caption for images. The handler has been tested 5 images and the output is as expected

Don't delete below this line.

---

## Required Information

- [x] I referenced the issue addressed in this PR.
- [x] I described the changes made and how these address the issue.
- [ ] I described how I tested these changes.

## Coding/Commit Requirements

* [x] I followed applicable coding standards (e.g., [PEP8](https://pep8.org/))
* [x] I have not committed any models or other large files.

## New Component Checklist (**mandatory** for new microservices)

* [x] I added an entry to `docker-compose.yml` and `build.yml`.
* [x] I created A CI workflow under `.github/workflows`.

### CODE REVIEW

**Comment by rohanakut** [comment]
@jeffbl I have added the Readme

**Comment by JRegimbal** [comment]
Nearly 1 GB of large files are committed here via language tool. This **should not** be merged without history being rewritten. Ideally, this would come as a new PR.

**Comment by jeffbl** [comment]
Assigning back to @rohanakut to fix the extraneous files, which must not be merged.

**Comment by rohanakut** [comment]
@jeffbl PR #779  has been created that does not have the language tools history. Please feel free to close this PR if everything else is in order with PR #779 .

**Comment by jeffbl** [comment]
Assigning to @rohanakut , to close when new PR is clean and ready to go.

**Comment by rohanakut** [comment]
Closing this PR as the new PR #779 is tested and works as expected

**Comment by rohanakut** [comment]
@jeffbl deleting the branch

**Pull request closed without merging**
