### PR TITLE
remove restrictive pattern on api_request format as it is causing iss…

### PR DESCRIPTION
**Pull request by BenMacnaughton**
…ues with validation and poses no threat to cause any downstream problems

Please ensure you've followed the checklist and provide all the required information *before* requesting a review.

## Required Information

- [x] Reference the issue this is meant to fix or describe it if none exists.
- [x] Full description of changes made.

## Pull Request Checklist

- [x] Coding standards are followed (e.g., [PEP8](https://pep8.org/))
- [x] An entry exists for the container in `docker-compose.yml` or `build.yml`
- [x] The Docker image builds
- [x] The container runs correctly when sent inputs with the changes
- [x] No models or other large files are part of these commits
- [x] A description of the tests already run as part of this PR is present

### CODE REVIEW

**Review by JRegimbal — COMMENTED** [review]
Don't really know what the issue is! We have updated the [URL definition used elsewhere](https://github.com/Shared-Reality-Lab/IMAGE-server/blob/47be5c8b5c0a563513ea021c0844ff140ada0987/definitions.json#L31) because they ended up being too restrictive before. Would that work for your case?

**Comment by BenMacnaughton** [comment]
Unfortunately, it does not since the extra arguments in the API call cause it to fail. I have just tested it and think that it might be best to leave the field unrestricted since there are a number of arguments that we may add or remove.

**Comment by JRegimbal** [comment]
Can you give an example of a possible API call?

**Comment by BenMacnaughton** [comment]
After looking around a bit it turned out to be a whitespace issue in the autour preprocessor that I will update. Looks like the pattern you referenced should be good for this.

**Comment by JRegimbal** [comment]
Looks like I gave you the same pattern we started with without noticing...closing since there's now no difference between this branch and schemas.

**Pull request closed without merging**
