### PR TITLE
Updated file versions

### PR DESCRIPTION
**Pull request by rohanakut**
In order to keep the files up to date and maintain the security patches, I have updated a few versions of the files. The following preprocessors were modified:
```
1. First Categoriser
2. Second Categoriser
3. Grouping 
```

The `first categoriser and grouping` have been tested on unicorn. However, the `second categoriser` **cannot be tested** on unicorn due to API KEY limitations.

### CODE REVIEW

**Comment by jeffbl** [comment]
@rohanakut out of curiosity what is the API key limitation?

**Comment by rohanakut** [comment]
I do not have the API key for second categoriser, as the API key is only present on a env file on pegasus.

**Comment by jeffbl** [comment]
OK. I think you have access to pegasus, so should have access to the .env file, but I may be misunderstanding the issue?

**Comment by rohanakut** [comment]
@jeffbl I have tested the second categorsier on unicorn and these changes do not break the pipeline. @jaydeepsingh25 if there aren't any further changes I believe this PR can be merged

**Review by jaydeepsingh25 — APPROVED** [review]

**Pull request merged**
