### PR TITLE
Added grouping schema

### PR DESCRIPTION
**Pull request by rohanakut**

### CODE REVIEW

**Review by JRegimbal — CHANGES_REQUESTED** [review]
Fix formatting on the JSON and remove the .DS_STORE first.

**Review by JRegimbal — CHANGES_REQUESTED** [review]
Add documentation of what should actually go in here using the description tags.

**Review by JRegimbal — CHANGES_REQUESTED** [review]

**Review by JRegimbal — CHANGES_REQUESTED** [review]

**Review by rohanakut — COMMENTED** [review]
The array of array of objects is chosen because according to my logic an array of object would hold a list of IDs which have same type. Hence an array of array of objects would then hold multiple such arrays and thereby support grouping of multiple objects. If i were to consider just an array of objects then it would allow me to do just 1 grouping

**Review by JRegimbal — APPROVED** [review]
Looks good. Verify that the structure we discussed passes validation against it and then you can merge it.

**Pull request merged**
